name = "signal0xl-ranking"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

# Cron de 1 minuto
[triggers]
crons = ["* * * * *"]

[vars]
RPC_URL = "https://rpc.testnet.arc.network"
CONTRACT_ADDRESS = "0x108E51F9af4aF2D8CAa1f41E81b91B84B1304d36"

# Binding de D1
[[d1_databases]]
binding = "RANKING_DB"
database_name = "signal0xl-db"
database_id = "8878bd59-8a2f-4a7a-9999-32a10251ec0d"
